### ISSUE TITLE
Using latest amazon-congito-indentity-js with IE11 and a Fetch Polyfill?

### ISSUE THREAD

**Issue by elgordino** [paulcwatts/ember-cognito#119]
Using ember-cognito with version `1.31.0` of `amazon-cognito-identity-js` works fine in IE11. I would like to use it with the latest `3.0.9` because the package is much smaller, but that build relies on fetch which does not exist in IE11.

I tried adding `ember-fetch` but I guess this only applies to the ember environment and the amazon-cognito stuff exists outside that. Is there a recommended way to add a fetch polyfill that will work with amazon-cognit-identity-js.

**Comment by paulcwatts** [comment]
Hi @elgordino ,

I don't know if I have a "recommended" way, but I solve it just by assigning the `ember-fetch` polyfill to the global fetch. So I have this in my `app.js`:

```javascript
import fetch from "fetch";

if (typeof FastBoot === "undefined") {
  if (window.fetch === undefined) {
    window.fetch = fetch;
  }
}
```

(If you don't use FastBoot, you can remove that check.)

I hope this helps!

**Comment by elgordino** [comment]
Thanks that helps a bunch, I'll do that. Cheers!
