### ISSUE TITLE
Module not found: Error: Can't resolve 'crypto'

### ISSUE THREAD

**Issue by rwwagner90** [paulcwatts/ember-cognito#159]
```
WARNING in ./node_modules/amazon-cognito-identity-js/es/utils/cryptoSecureRandomInt.js
Module not found: Error: Can't resolve 'crypto' in '/Users/rwwagner90/shipshape/swach/node_modules/amazon-cognito-identity-js/es/utils'
 @ ./node_modules/amazon-cognito-identity-js/es/utils/cryptoSecureRandomInt.js
 @ ./node_modules/amazon-cognito-identity-js/es/utils/WordArray.js
 @ ./node_modules/amazon-cognito-identity-js/es/AuthenticationHelper.js
 @ ./node_modules/amazon-cognito-identity-js/es/index.js
 @ /private/var/folders/2p/61j5p9d56ln49n5wf1jc5q3r0000gn/T/broccoli-2336901HrgXZ0Ik4L/cache-546-bundler/staging/tests.js
 @ multi /private/var/folders/2p/61j5p9d56ln49n5wf1jc5q3r0000gn/T/broccoli-2336901HrgXZ0Ik4L/cache-546-bundler/staging/l.js /private/var/folders/2p/61j5p9d56ln49n5wf1jc5q3r0000gn/T/broccoli-2336901HrgXZ0Ik4
```

Any ideas how to resolve this?

**Comment by paulcwatts** [comment]
I haven't seen that error. What version of Ember is it? Or of amplify?

**Comment by rwwagner90** [comment]
@paulcwatts if you install this addon in an app and run it, you'll get the error in your terminal. We're on latest Ember, but I don't think the Ember version has any bearing on this.

**Comment by paulcwatts** [comment]
Sorry, I should have time to look this (and the PR) today.

**Comment by paulcwatts** [comment]
I merged the PR (thank you!), but unfortunately it doesn't clear the warning. The only thing I can think is some issue with the newer version of `amazon-cognito-identity-js`, since it doesn't happen in my apps and I'm on 4.3 of that library. Perhaps try pinning that library?

**Comment by rwwagner90** [comment]
@paulcwatts I think this might fix it https://github.com/paulcwatts/ember-cognito/pull/161

If I understand the problem correctly, `crypto` was built into node, and webpack polyfilled it automatically before, but does not anymore. This should add back the polyfill.

**Comment by paulcwatts** [comment]
Wow, great find!

**Comment by rwwagner90** [comment]
Thanks! Please let me know if it works.

**Comment by rwwagner90** [comment]
@paulcwatts have you tested to see if this fix worked?

**Comment by paulcwatts** [comment]
I did, it seems to work -- I merged your PR and released a new version.

**Comment by rwwagner90** [comment]
@paulcwatts awesome, glad to hear it!
