### ISSUE TITLE
Add support for user migration Lambda trigger

### ISSUE THREAD

**Issue by JoseLawrence** [paulcwatts/ember-cognito#91]
To enable user migration on the app, authentication flow should be set to `USER_PASSWORD_AUTH`. 
https://docs.aws.amazon.com/cognito/latest/developerguide/using-amazon-cognito-javascript-sdk-user-migration-lambda.html?shortFooter=true

Is there any plan to add this feature, please? 

Thanks in advance.

**Comment by paulcwatts** [comment]
Hi @JoseLawrence!

It's a good feature to add, though I didn't have any plans for it. 

If you wanted to create a PR for it, one way I could see adding support would be to create a configuration option called `authenticationFlowType`, similar to the `clientId` and `poolId`. 

This option could be set in the `ENV.cognito` hash, wired through the `cognito` service, and used in the authenticator's `authenticate` method just before the call to `authenticateUser`.

**Comment by JoseLawrence** [comment]
Perfect, sounds good @paulcwatts 
I will create a PR once I am ready. Cheers!

**Comment by JoseLawrence** [comment]
Hey @paulcwatts added the support for `authenticationFlowType` 
PR for review pls - https://github.com/paulcwatts/ember-cognito/pull/92

**Comment by JoseLawrence** [comment]
Support added now.
