### ISSUE TITLE
Breaking change in amazon-cognito-identity-js@2.0.14

### ISSUE THREAD

**Issue by JoseLawrence** [paulcwatts/ember-cognito#99]
Hi Guys, Not really an issue for ember-cognito but just wanted to understand if anybody else facing this issue. I am getting this issue (https://github.com/aws-amplify/amplify-js/issues/1243) in my app.  Also getting the same error when I run the tests within ember-cognito repo. So just wanted to understand if everybody is facing this issue. 
Thanks!

**Comment by paulcwatts** [comment]
greenkeeper did run into it on one of its branches, but I haven't had time to investigate: https://travis-ci.org/paulcwatts/ember-cognito/jobs/404921159

**Comment by paulcwatts** [comment]
I published v0.9.1 which includes a workaround for this. However, it's still brittle and I will need to do some extra work to make this more resilient to changes to the Amazon library.

**Comment by JoseLawrence** [comment]
Brill, Thanks for the quick workaround @paulcwatts

**Comment by paulcwatts** [comment]
https://github.com/paulcwatts/ember-cognito/pull/129
